import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

import numpy as np
import pandas as pd

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)

def _find_smart_meter_path() -> str:
    raw_dir = os.path.join(_ROOT, "data", "raw")
    candidates = [
        "CEEW - Smart meter data Mathura 2020.csv",
        "CEEW - Smart meter data Bareilly 2020.csv",
    ]
    for c in candidates:
        p = os.path.join(raw_dir, c)
        if os.path.exists(p):
            return p
    if os.path.exists(raw_dir):
        for f in os.listdir(raw_dir):
            if f.startswith("CEEW") and f.endswith(".csv"):
                return os.path.join(raw_dir, f)
    return os.path.join(raw_dir, candidates[0])

SMART_METER_PATH = _find_smart_meter_path()
WEATHER_PATH = os.path.join(_ROOT, "data", "raw", "weather.csv")
PROCESSED_PATH = os.path.join(_ROOT, "data", "processed", "merged_hourly.csv")

EMISSION_FACTOR_KG_PER_KWH: float = 0.82

METER_ID = None


def _load_smart_meter(path: str) -> pd.DataFrame:
    """
    Load the CEEW Mathura 2020 CSV.

    Confirmed columns:
        x_Timestamp          → datetime index
        t_kWh                → energy consumed per 3-min window (kWh)
        z_Avg Voltage (Volt) → average voltage (V)
        z_Avg Current (Amp)  → average current (A)
        y_Freq (Hz)          → grid frequency (Hz)
        meter                → meter ID (MH01 … MH47)
    """
    print(f"[1/5] Loading smart meter CSV … ({path})")
    print("      (3.7 M rows — may take 10–20 seconds)")

    df = pd.read_csv(
        path,
        parse_dates=["x_Timestamp"],
        low_memory=False,
    )

    print(f"      Raw shape  : {df.shape}")
    print(f"      Meters     : {sorted(df['meter'].unique().tolist())}")
    print(f"      Date range : {df['x_Timestamp'].min()} → {df['x_Timestamp'].max()}")
    print(f"      NaNs       : {df.isnull().sum().sum()}")

    df = df.rename(
        columns={
            "x_Timestamp": "datetime",
            "t_kWh": "energy_kwh",
            "z_Avg Voltage (Volt)": "voltage_v",
            "z_Avg Current (Amp)": "current_a",
            "y_Freq (Hz)": "frequency_hz",
        }
    )

    df = df.set_index("datetime").sort_index()

    if METER_ID is not None:
        df = df[df["meter"] == METER_ID]
        print(f"      Filtered to meter : {METER_ID}  →  {len(df)} rows")

    df = df.drop(columns=["meter"])

    return df


def _resample_to_hourly(df: pd.DataFrame) -> pd.DataFrame:
    """
    Two operations in one step:

    1. GROUP BY timestamp — average electrical readings across all meters
       that share the same 3-minute slot.
       (energy_kwh is SUMMED across meters; voltage/current/freq are averaged)

    2. RESAMPLE to 1-hour windows — aggregate the 3-min data to hourly.
       energy_kwh  → sum   (total kWh consumed in the hour across all meters)
       voltage_v   → mean  (average voltage)
       current_a   → mean  (average current)
       frequency_hz→ mean  (average frequency)
    """
    print("[2/5] Aggregating across meters and resampling → 1-hour …")

    agg_3min = df.groupby(df.index).agg(
        {
            "energy_kwh": "sum",
            "voltage_v": "mean",
            "current_a": "mean",
            "frequency_hz": "mean",
        }
    )

    print(
        f"      After meter aggregation : {agg_3min.shape}  "
        f"({agg_3min.index.min()} → {agg_3min.index.max()})"
    )

    hourly = agg_3min.resample("1h").agg(
        {
            "energy_kwh": "sum",
            "voltage_v": "mean",
            "current_a": "mean",
            "frequency_hz": "mean",
        }
    )

    hourly["active_power_kw"] = hourly["energy_kwh"]

    print(f"      Hourly shape : {hourly.shape}")
    print(f"      Date range   : {hourly.index.min()} → {hourly.index.max()}")
    print(f"      energy_kwh sample stats:\n{hourly['energy_kwh'].describe()}")
    return hourly


def _load_weather(path: str) -> pd.DataFrame:
    """
    Load the Open-Meteo weather CSV (generated by download_weather.py).

    Confirmed columns (already renamed by download script):
        datetime, temperature_c, humidity_pct, precipitation_mm,
        wind_speed_ms, cloud_cover_pct, solar_radiation_wm2
    """
    print(f"[3/5] Loading weather data … ({path})")

    df = pd.read_csv(path, parse_dates=["datetime"], index_col="datetime")

    print(f"      Weather shape : {df.shape}")
    print(f"      Columns       : {df.columns.tolist()}")
    print(f"      Date range    : {df.index.min()} → {df.index.max()}")
    print(f"      NaNs          : {df.isnull().sum().sum()}")

    # Ensure exactly hourly
    df = df.resample("1h").mean()
    return df


def _merge_datasets(smart_hourly: pd.DataFrame, weather: pd.DataFrame) -> pd.DataFrame:
    """Inner-join smart meter and weather on DatetimeIndex."""
    print("[4/5] Merging smart meter ⟕ weather on DatetimeIndex …")

    merged = smart_hourly.join(weather, how="inner")
    merged = merged.loc[:, ~merged.columns.duplicated()]

    print(f"      Merged shape (pre-clean) : {merged.shape}")
    return merged


def _reindex_continuous_hourly(df: pd.DataFrame) -> pd.DataFrame:
    """
    Force a gapless hourly DatetimeIndex between the first and last timestamp.

    XGBoost's row-wise features don't care if hour 500 and hour 502 are
    3 hours apart in real time — each row is independent. A sequence model
    (LSTM/GRU) treats consecutive rows as consecutive hours; a silent missing
    hour would make it learn a fake 2-hour jump as if it were 1 hour. Doing
    this reindex BEFORE the fill/outlier step lets the existing ffill/bfill
    logic repair the newly-introduced NaN rows exactly like any other gap.
    """
    full_range = pd.date_range(df.index.min(), df.index.max(), freq="1h", name=df.index.name)
    missing = full_range.difference(df.index)
    if len(missing) > 0:
        print(f"      Reindexing to continuous hourly range — filling {len(missing)} missing hour(s)")
    df = df.reindex(full_range)
    return df


def _handle_missing(df: pd.DataFrame) -> pd.DataFrame:
    """
    0. Reindex to a gapless hourly range (see _reindex_continuous_hourly).
    1. Clamp voltage to Indian grid tolerance: 230V ± 10% → [180, 260] V.
    2. Clamp frequency to Indian grid standard: 50 Hz ± 3% → [48.5, 51.5] Hz.
    3. Remove negative energy readings (meter faults).
    4. Time-interpolate and ffill/bfill all features so sequence models (LSTM) receive 0 NaNs.
    """
    print("[5/5] Cleaning missing values & outliers …")

    df = _reindex_continuous_hourly(df)

    if "voltage_v" in df.columns:
        out_v = (df["voltage_v"] < 180) | (df["voltage_v"] > 260)
        df.loc[out_v, "voltage_v"] = np.nan
        print(f"      Voltage outliers clamped : {out_v.sum()}")

    if "frequency_hz" in df.columns:
        out_f = (df["frequency_hz"] < 48.5) | (df["frequency_hz"] > 51.5)
        df.loc[out_f, "frequency_hz"] = np.nan
        print(f"      Frequency outliers clamped : {out_f.sum()}")

    if "energy_kwh" in df.columns:
        neg = df["energy_kwh"] < 0
        if neg.sum() > 0:
            df.loc[neg, "energy_kwh"] = np.nan
            print(f"      Negative energy rows clamped : {neg.sum()}")

    num_cols = df.select_dtypes(include=np.number).columns
    for col in num_cols:
        df[col] = (
            df[col]
            .interpolate(method="time", limit_direction="both")
            .ffill()
            .bfill()
        )

    print(f"      Final shape            : {df.shape}")
    print(f"      Remaining NaNs         : {df.isnull().sum().sum()}")
    return df


def load_and_prepare_data(
    smart_meter_path: str = SMART_METER_PATH,
    weather_path: str = WEATHER_PATH,
    save_processed: bool = True,
) -> pd.DataFrame:
    """
    Full Phase 1 pipeline. Returns a clean, merged, hourly DataFrame.

    Output columns:
        energy_kwh        — total kWh across all meters per hour  [TARGET]
        active_power_kw   — same value expressed as average kW
        voltage_v         — mean voltage across meters (V)
        current_a         — mean current across meters (A)
        frequency_hz      — mean grid frequency (Hz)
        temperature_c     — ambient temperature (°C)
        humidity_pct      — relative humidity (%)
        precipitation_mm  — precipitation (mm)
        wind_speed_ms     — wind speed (m/s)
        cloud_cover_pct   — cloud cover (%)
        solar_radiation_wm2 — shortwave radiation (W/m²)

    Index: DatetimeIndex, hourly, Asia/Kolkata timezone
    """
    for fpath in [smart_meter_path, weather_path]:
        if not os.path.exists(fpath):
            raise FileNotFoundError(
                f"File not found: '{fpath}'\n"
                "Ensure CSVs are in data/raw/ and download_weather.py has been run."
            )

    smart_raw = _load_smart_meter(smart_meter_path)
    smart_hourly = _resample_to_hourly(smart_raw)
    weather = _load_weather(weather_path)
    merged = _merge_datasets(smart_hourly, weather)
    clean = _handle_missing(merged)

    gaps = clean.index.to_series().diff().dropna().unique()
    assert len(gaps) == 1 and gaps[0] == pd.Timedelta("1h"), (
        f"Index is not perfectly hourly after cleaning — found gap(s): {gaps}. "
        "A sequence model (LSTM/GRU) needs a gapless index; investigate before training."
    )

    if save_processed:
        os.makedirs(os.path.dirname(PROCESSED_PATH), exist_ok=True)
        clean.to_csv(PROCESSED_PATH)
        print(f"\n  ✔ Processed data saved → {PROCESSED_PATH}")

    print("\n" + "=" * 62)
    print("  PHASE 1 COMPLETE — Final DataFrame Summary")
    print("=" * 62)
    print(f"  Shape            : {clean.shape[0]} rows × {clean.shape[1]} cols")
    print(f"  Date range       : {clean.index.min()} → {clean.index.max()}")
    print(f"  Columns          : {clean.columns.tolist()}")
    print(f"  Remaining NaNs   : {clean.isnull().sum().sum()}")
    print(
        f"\n  energy_kwh (total across all {len(sorted(pd.read_csv(smart_meter_path, usecols=['meter'])['meter'].unique()))} meters):"
    )
    print(clean["energy_kwh"].describe().to_string())
    print("=" * 62 + "\n")

    return clean


if __name__ == "__main__":
    df = load_and_prepare_data()
    print("\nFirst 10 rows of clean hourly data:")
    print(df.head(10).to_string())
    